"""Holdings Migration.

Revision ID: 0e78ad7fbdcf
Revises: 058d3c022c1a
Create Date: 2021-04-11 22:39:54.375791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e78ad7fbdcf'
down_revision = '058d3c022c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('cmp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'cmp')
    # ### end Alembic commands ###
